### Create new patient entity
POST http://localhost:4000/patients/create
Content-Type: application/json

{
  "name": "Ajay2",
  "email": "Ajay@example.com",
  "address": "123, Perangi medu",
  "dateOfBirth": "2003-12-25",
  "registeredDate": "2025-12-23"
}