### Create new patient entity
POST http://localhost:4004/api/patients/create
Content-Type: application/json

{
  "name": "Ajay kafka 1",
  "email": "Akafka_124@example.com",
  "address": "123, Perangi medu",
  "dateOfBirth": "2003-12-25",
  "registeredDate": "2025-12-23"
}
